name: Clean BlockAds Plugin

on:
  schedule:
    - cron: "0 18 * * *"  # 每天凌晨2点（UTC+0，所以是北京时间早上2点）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Fetch latest blockAds.plugin
        run: |
          curl -o blockAds_origin.plugin https://raw.githubusercontent.com/fmz200/wool_scripts/main/Loon/plugin/blockAds.plugin

      - name: Clean pangolin rules
        run: |
          grep -vE 'pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b' blockAds_origin.plugin > blockAds_clean.plugin

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add blockAds_clean.plugin || echo "Nothing to add"
          git commit -m "Auto update clean blockAds.plugin" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
