name: Clean Four Plugins

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch all plugins (binary safe)
        run: |
          curl -L --output blockAds_origin.plugin https://raw.githubusercontent.com/fmz200/wool_scripts/main/Loon/plugin/blockAds.plugin
          curl -L --output StartUpAds_origin.plugin https://raw.githubusercontent.com/ddgksf2013/Plugins/main/Adblock/StartUpAds.plugin
          curl -L --output BlockAdvertisers_origin.plugin https://kelee.one/Tool/Loon/Plugin/BlockAdvertisers.plugin
          curl -L --output Remove_ads_by_keli_origin.plugin https://kelee.one/Tool/Loon/Plugin/Remove_ads_by_keli.plugin

      - name: Clean plugins
        run: |
          # 定义通用清理函数
          clean_plugin() {
            input="$1"
            output="$2"
            awk '
            BEGIN{mitm=0}
            /^mitm/ {mitm=1; print; next}
            mitm==1 && /^[^ ]/ {mitm=0}
            mitm==1 && /pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b|api-access\.pangolin-sdk-toutiao\.com/ {next}
            /pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b|api-access\.pangolin-sdk-toutiao\.com|api\/ad\/union\/sdk\/(get_ads|stats|settings)/ {next}
            {print}
            ' "$input" > "$output"
          }

          clean_plugin blockAds_origin.plugin blockAds_clean.plugin
          clean_plugin StartUpAds_origin.plugin StartUpAds_clean.plugin
          clean_plugin BlockAdvertisers_origin.plugin BlockAdvertisers_clean.plugin
          clean_plugin Remove_ads_by_keli_origin.plugin Remove_ads_by_keli_clean.plugin

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.plugin || true
          git commit -m "Auto update clean plugins" || echo "No changes to commit"
          git push || echo "No changes to push"