name: Clean Four Plugins

on:
  schedule:
    - cron: "0 2 * * *"  # 每天凌晨2点
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch all plugins
        run: |
          curl -o blockAds_origin.plugin https://raw.githubusercontent.com/fmz200/wool_scripts/main/Loon/plugin/blockAds.plugin
          curl -o StartUpAds_origin.plugin https://raw.githubusercontent.com/ddgksf2013/Plugins/main/Adblock/StartUpAds.plugin
          curl -o BlockAdvertisers_origin.plugin https://kelee.one/Tool/Loon/Plugin/BlockAdvertisers.plugin
          curl -o Remove_ads_by_keli_origin.plugin https://kelee.one/Tool/Loon/Plugin/Remove_ads_by_keli.plugin

      - name: Convert encoding (GBK to UTF-8)
        run: |
          iconv -f gbk -t utf-8 BlockAdvertisers_origin.plugin -o BlockAdvertisers_utf8.plugin || cp BlockAdvertisers_origin.plugin BlockAdvertisers_utf8.plugin
          iconv -f gbk -t utf-8 Remove_ads_by_keli_origin.plugin -o Remove_ads_by_keli_utf8.plugin || cp Remove_ads_by_keli_origin.plugin Remove_ads_by_keli_utf8.plugin

      - name: Clean plugins
        run: |
          awk '
          /^mitm/ {mitm=1; print; next}
          mitm && /^[^ ]/ {mitm=0}
          mitm && /pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b|api-access\.pangolin-sdk-toutiao\.com/ {next}
          {print}
          ' blockAds_origin.plugin | grep -vE 'pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b|api-access\.pangolin-sdk-toutiao\.com|api\/ad\/union\/sdk\/(get_ads|stats|settings)' > blockAds_clean.plugin

          awk '
          /^mitm/ {mitm=1; print; next}
          mitm && /^[^ ]/ {mitm=0}
          mitm && /pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b|api-access\.pangolin-sdk-toutiao\.com/ {next}
          {print}
          ' StartUpAds_origin.plugin | grep -vE 'pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b|api-access\.pangolin-sdk-toutiao\.com|api\/ad\/union\/sdk\/(get_ads|stats|settings)' > StartUpAds_clean.plugin

          awk '
          /^mitm/ {mitm=1; print; next}
          mitm && /^[^ ]/ {mitm=0}
          mitm && /pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b|api-access\.pangolin-sdk-toutiao\.com/ {next}
          {print}
          ' BlockAdvertisers_utf8.plugin | grep -vE 'pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b|api-access\.pangolin-sdk-toutiao\.com|api\/ad\/union\/sdk\/(get_ads|stats|settings)' > BlockAdvertisers_clean.plugin

          awk '
          /^mitm/ {mitm=1; print; next}
          mitm && /^[^ ]/ {mitm=0}
          mitm && /pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b|api-access\.pangolin-sdk-toutiao\.com/ {next}
          {print}
          ' Remove_ads_by_keli_utf8.plugin | grep -vE 'pangolin-sdk-toutiao|pangolin-sdk-toutiao1|pangolin-sdk-toutiao-b|api-access\.pangolin-sdk-toutiao\.com|api\/ad\/union\/sdk\/(get_ads|stats|settings)' > Remove_ads_by_keli_clean.plugin

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add blockAds_clean.plugin StartUpAds_clean.plugin BlockAdvertisers_clean.plugin Remove_ads_by_keli_clean.plugin || true
          git commit -m "Auto update clean plugins" || echo "No changes to commit"
          git push || echo "No changes to push"